### ISSUE TITLE
Direct URL links result in 404

### ISSUE THREAD

**Issue by onyxraven** [blimmer/whichben#6]
eg http://whichben.com/found/5

I believe this is caused by being hosted on s3 but s3 doesn't have a catch-all which will re-send the proper index page.

**Comment by blimmer** [comment]
I need to configure it like this :
https://github.com/Kerry350/ember-deploy-s3-index/pull/12/files

On Thursday, May 28, 2015, Justin Hart notifications@github.com wrote:

> eg http://whichben.com/found/5
> 
> I believe this is caused by being hosted on s3 but s3 doesn't have a
> catch-all which will re-send the proper index page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blimmer/whichben/issues/6.

## 

Ben Limmer
Software Developer
ben@ibotta.com

[sent from my mobile]

**Comment by blimmer** [comment]
Updated on S3. Should work now.

**Comment by onyxraven** [comment]
Confirmed! :hamster:
